version: '3'
services:
  postgres:
    image: postgres:15-bullseye
    environment:
      POSTGRES_DB: shopapp
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 65432:5432
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/1_init.sql