server:
  port: 8080
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    cors:
      allowed-origins: http://localhost:4200
  datasource:
    url: jdbc:postgresql://localhost:65432/shopapp
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
api:
  prefix: api/v1
jwt:
  expiration: 2592000 #30 days = 30*24*60*60
  secretKey: 9C40hc9UHvQId20zKNQm3G1duJrY//DNq8pkX/J88QI=
# It not use for production
logging.level.org.springframework.security: DEBUG